local options = {
	-- 1. Important
	compatible = false,
	cpoptions = "aABceFs_",
	paste = true,
	-- runtimepath,
	-- packpath,
	helpfile = "/usr/share/nvim/runtime/doc/help.txt",

	-- 2. Moving around, searching and patterns
	whichwrap = "b,s",
	startofline  = false,
	paragraphs = "IPLPPPQPP TPHPLIPpLPItpplpipbp",
	sections = "SHNHH HUnhsh",
	path = ".,,",
	cdhome = true,
	cdpath = ",,",
	autochdir = false,
	wrapscan = true,
	incsearch = true,
	magic = true,
	regexpengine = 0,
	ignorecase = false,
	smartcase = false,
	casemap = "internal,keepascii",
	maxmempattern = 100000,
	define = "",
	include = "",
	includeexpr = "",

	-- 3. Tags
	tagbsearch = true,
	taglength = 0,
	tags = "./tags;,tags",
	tagcase = "followic",
	tagrelative = true,
	tagstack = true,
	showfulltag = false,
	tagfunc = "", 

	-- 4. Displaying text
	scroll = 7,
	smoothscroll = false,
	scrolloff = 0,
	wrap = false,
	linebreak = true,
	breakindent = false,
	breakindentopt = "",
	-- breakat,
	showbreak = "",
	sidescroll = 1,
	sidescrolloff = 0,
	display = "lastline",
	fillchars = "",
	cmdheight = 1,
	-- columns,
	-- lines,
	-- window,
	lazyredraw = false,
	redrawtime = 2000,
	writedelay = 0,
	list = true,
	listchars = {
		tab = "  ",
		trail = "·",
		extends = ">",
	},
	number = true,
	relativenumber = true,
	numberwidth = 5,
	conceallevel = 0,
	concealcursor = "",

	-- 5. Syntax, highlighting and spelling
	background = "dark",
	filetype = "",
	syntax = "",
	synmaxcol = 10000,
	hlsearch = true,
	termguicolors = true,
	cursorcolumn = false,
	cursorline = true,
	cursorlineopt = "number,line",
	colorcolumn = "",
	spell = true,
	spelllang = "en,fr",
	spellfile = "",
	-- spellcapcheck,
	spelloptions = "",
	spellsuggest = "best",
	mkspellmem = "460000,2000,500",

	-- 6. Multiple Windows
	laststatus = 2,
	statuscolumn = "",
	statusline = "%f %= %l,%c%V %p%%",
	equalalways = true,
	eadirection = "both",
	winheight = 1,
	winminheight = 1,
	winfixbuf = false,
	winfixheight = false,
	winfixwidth = false,
	winwidth = 20,
	winminwidth = 1,
	helpheight = 20,
	previewheight = 12,
	previewwindow = false,
	hidden = true,
	switchbuf = "newtab",
	splitbelow = false,
	splitkeep = "cursor",
	splitright = false,
	scrollbind = false,
	scrollopt = "ver,jump",
	cursorbind = false,

	-- 7. Multiple tab pages
	showtabline = 1,
	tabclose = "uselast",
	tabpagemax = 50,
	tabline = "",

	-- 8. Terminal
	scrolljump = 1,
	title = true,
	titlelen = 85,
	titlestring = "Neovim",
	titleold = "",
	icon = false,
	iconstring = "",

	-- 9. Using the mouse
	mouse = "nvi",
	mousemodel = "popup_setpos",
	mousetime = 500,

	-- 10. Messages and info
	terse = false,
	shortmess = "ltToOCF",
	messagesopt = "hit-enter,history:1000",
	showcmd = true,
	showcmdloc = "last",
	showmode = true,
	ruler = true,
	rulerformat = "%17(%c%V %p%%%)",
	report = 2,
	verbose = 0,
	verbosefile = "",
	more = true,
	confirm = false,
	errorbells = false,
	visualbell = true,
	belloff = "all",
	helplang = "en",

	-- 11. Selecting text
	selection = "inclusive",
	selectmode = "",
	clipboard = "",
	keymodel = "",

	-- 12. Editing text
	undolevels = 1000,
	undofile = false,
	undodir = "",
	undoreload = 10000,
	modified = false,
	readonly = false,
	modifiable = true,
	textwidth = 0,
	wrapmargin = 0,
	backspace = "indent,eol,start",
	-- comments,
	formatoptions = "tcqj",
	-- formatlistpat
	formatexpr = "",
	complete = ".,w,b,u,t",
	completeopt = "menu,popup",
	completeitemalign = "abbr,kind,menu",
	pumheight = 0,
	pumwidth = 15,
	completefunc = "",
	omnifunc = "",
	dictionary = "",
	thesaurus = "",
	thesaurusfunc = "",
	infercase = false,
	digraph = false,
	tildeop = false,
	operatorfunc = "",
	showmatch = false,
	matchtime = 5,
	-- matchpairs,
	joinspaces = false,
	nrformats = "bin,hex",

	-- 13. Tabs and indenting
	tabstop = 4,
	shiftwidth = 4,
	vartabstop = "",
	varsofttabstop = "",
	smarttab = true,
	softtabstop = 4,
	shiftround = false,
	expandtab = true,
	autoindent = true,
	smartindent = true,
	cindent = false,
	cinoptions = "",
	-- cinkeys,
	-- cinwords,
	-- cinscopedecls
	indentexpr = "",
	-- indentkeys,
	copyindent = true,
	preserveindent = false,
	lisp = false,
	-- lipswords,
	--lispoptions

	-- 14. Folding
	foldenable = true,
	foldlevel = 0,
	foldlevelstart = 99,
	foldcolumn = "5",
	foldtext = "foldtext()",
	foldclose = "",
	foldopen = "block,hor,mark,percent,quickfix,search,tag,undo",
	foldminlines = 1,
	commentstring = "",
	foldmethod = "syntax",
	-- foldexpr,
	-- foldignore,
	-- foldmarker,
	foldnestmax = 20,

	-- 15. Diff mode
	diff = false,
	-- diffopt,
	-- diffexpr,
	-- patchexpr,

	-- 16. Mapping
	maxmapdepth = 1000,
	timeout = true,
	ttimeout = true,
	timeoutlen = 1000,
	ttimeoutlen = 50,

	-- 17. Reading and writing files
	modeline = true,
	modelineexpr = false,
	modelines = 5,
	binary = false,
	endofline = true,
	endoffile = false,
	fixendofline = true,
	bomb = false,
	fileformat = "unix",
	fileformats = "unix",
	write = true,
	writebackup = true,
	backup = false,
	backupskip = "/tmp/*",
	backupcopy = "auto",
	-- backupdir,
	backupext = ".bak",
	autowrite = false,
	autowriteall = false,
	writeany = false,
	autoread = true,
	patchmode = "",
	fsync = true,

	-- 18. The swap file
	-- directory,
	swapfile = true,
	updatecount = 200,
	updatetime = 4000,

	-- 19. Command line editing
	history = 10000,
	wildchar = 9,
	wildcharm = 0,
	wildmode = "full",
	-- suffixes
	suffixesadd = "",
	wildignore = "",
	fileignorecase = false,
	wildignorecase = false,
	wildmenu = true,
	-- cedit
	cmdwinheight = 7,

	-- 20. Executing external commands
	shell = "$SHELL",
	shellquote = "",
	shellxquote = "",
	shellxescape = "",
	shellcmdflag = "-c",
	-- shellredir,
	shelltemp = true,
	equalprg = "",
	formatprg = "",
	keywordprg = ":Man",
	warn = true,

	-- 21. Running make and jumping to errors (quickfix)
	errorfile = "errors.err",
	-- errorformat,
	makeprg = "make",
	-- shellpipe,
	makeef = "",
	-- grepprg,
	-- grepformat,
	makeencoding = "",

	-- 22. Language specific
	-- isfname,
	-- isident,
	-- iskeyword,
	-- isprint,
	-- quoteescape,
	-- rightleft,
	-- rightleftcmd,
	revins = false,
	allowrevins = false,
	-- aleph,
	hkmap = false,
	hkmapp = false,
	arabic = false,
	arabicshape = true,
	termbidi = false,
	-- keymap,
	-- langmap,
	-- langremap,
	-- iminsert,
	-- imsearch,

	-- 23. Multi-byte characters
	encoding = "utf-8",
	fileencoding = "",
	fileencodings = "ucs-bom,utf-8,default,latin1",
	charconvert = "",
	delcombine = false,
	maxcombine = 6,
	ambiwidth = "single",
	emoji = true,

	-- 24. Various
	virtualedit = "",
	eventignore = "",
	eventignorewin = "",
	loadplugins = true,
	exrc = false,
	secure = false,
	gdefault = false,
	maxfuncdepth = 100,
	-- sessionoptions,
	-- viewoptions,
	-- viewdir,
	-- viminfo,
	bufhidden = "",
	buftype = "",
	buflisted = true,
	debug = "",
	signcolumn = "auto"
}

for option, value in pairs(options) do
	vim.opt[option] = value
end

